### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by TurtleP** [TurtleP/Turtle-Tale#18]
- [ ] Another area or two between home and Beach (for mechanics/tutorial)
- [ ] Most enemies will die easily from shoulder bash unless specified (like bosses or tougher enemies)
- [ ] Add Fish to one of the new areas. They can be stomped on.

This will be updated as needed.
